/* 정적 이력의 실제 최고·평균 경락가와 당일 수집 상태를 차트에 표시한다. */
(() => {
  const apiGrade = g => g === "중" ? "보통" : g;
  const gradeLabel = g => g === "중" ? "보통" : g;
  const won = n => `₩${Math.round(n || 0).toLocaleString("ko-KR")}`;
  const number = v => Number(String(v ?? "").replace(/[^0-9.-]/g, "")) || 0;
  const cache = new WeakMap(), prepared = new WeakSet();
  const dates = days => Array.from({ length: days }, (_, i) => { const d = new Date(); d.setHours(12, 0, 0, 0); d.setDate(d.getDate() - (days - 1 - i)); return d; });
  const daysOf = card => Number(card.querySelector("svg")?.getAttribute("aria-label")?.match(/(7|30)일/)?.[1] || 7);

  function priceInfo(card, points, grade, index) {
    const point = points[index], date = dates(points.length)[index], price = card.querySelector(".market-price"), clock = card.querySelector(".market-clock");
    if (price && point.status !== "pending") { price.firstChild.textContent = won(point.max); const sub = price.querySelector("small"); if (sub) sub.textContent = ` / ${point.unit} · 평균 ${won(point.avg)}`; }
    if (!clock) return;
    const label = gradeLabel(grade);
    clock.textContent = point.status === "pending" ? `🕘 ${date.getMonth() + 1}월 ${date.getDate()}일 · 오늘 경락가 수집 대기 중` : point.status === "closed" ? `🕘 ${date.getMonth() + 1}월 ${date.getDate()}일 · 휴장/거래 없음 · 직전 거래일 ${label}등급 최고가 ${won(point.max)}` : `🕘 ${date.getMonth() + 1}월 ${date.getDate()}일 · ${label}등급 최고 경락가 ${won(point.max)} · 평균 ${won(point.avg)}`;
  }

  function draw(card, points, grade, selected = points.length - 1, allGrades = {}) {
    const svg = card.querySelector("svg"); if (!svg) return;
    const values = points.map(p => p.max), w = 350, h = 190, l = 38, r = 14, t = 16, b = 38, cw = w - l - r, ch = h - t - b;
    const low = Math.min(...values), high = Math.max(...values), min = Math.floor(low / 10000) * 10000, max = Math.max(min + 10000, Math.ceil(high / 10000) * 10000);
    const x = i => l + cw * i / (values.length - 1), y = v => t + (max - v) / (max - min) * ch, dateList = dates(values.length), selectedIndex = Math.max(0, Math.min(values.length - 1, selected)), selectedPoint = points[selectedIndex], sx = x(selectedIndex), sy = y(values[selectedIndex]);
    const grid = Array.from({ length: Math.round((max - min) / 10000) + 1 }, (_, i) => { const v = max - i * 10000, yy = y(v); return `<line class="chart-grid" x1="${l}" x2="${l + cw}" y1="${yy}" y2="${yy}"/><text class="chart-axis" x="2" y="${yy + 4}">${Math.round(v / 10000)}만</text>`; }).join("");
    const pendingStart = points.findIndex(p => p.status === "pending"), solidEnd = pendingStart < 0 ? values.length : Math.max(1, pendingStart), solid = values.slice(0, solidEnd).map((v, i) => `${x(i)},${y(v)}`).join(" "), pending = pendingStart > 0 ? values.slice(pendingStart - 1).map((v, i) => `${x(pendingStart - 1 + i)},${y(v)}`).join(" ") : "", area = `${l},${t + ch} ${solid} ${x(solidEnd - 1)},${t + ch}`;
    const dots = values.map((v, i) => { const point = points[i], label = point.status === "closed" ? "휴" : point.status === "pending" ? "대기" : ""; return `<g class="chart-hit" data-grade-point="${i}"><circle class="chart-hit-area" cx="${x(i)}" cy="${y(v)}" r="16"/><circle class="chart-dot ${i === selectedIndex ? "selected" : ""} ${point.status}" cx="${x(i)}" cy="${y(v)}" r="${i === selectedIndex ? 5 : 3.2}"/>${label ? `<text class="chart-state-label ${point.status}" x="${x(i)}" y="${y(v) - 10}" text-anchor="middle">${label}</text>` : ""}</g>`; }).join("");
    const labels = dateList.map((d, i) => `<text class="chart-date ${values.length === 30 ? "compact" : ""}" x="${x(i)}" y="${h - 10}" text-anchor="middle">${d.getDate()}</text>`).join(""), closedBands = points.map((p, i) => p.status === "closed" ? `<rect class="chart-closed-band" x="${x(i) - Math.max(4, cw / (values.length - 1) / 2)}" y="${t}" width="${Math.max(8, cw / (values.length - 1))}" height="${ch}"/>` : "").join("");
    const pendingTip = selectedPoint.status === "pending", reference = allGrades["특"]?.[selectedIndex]?.max, ratio = target => reference && target?.max ? `${Math.round(target.max / reference * 100)}%` : "—", comparison = reference ? `특 100% · 상 ${ratio(allGrades["상"]?.[selectedIndex])} · 보통 ${ratio(allGrades["중"]?.[selectedIndex])}` : "특등급 비교 자료 없음", tw = 156, th = pendingTip ? 50 : 65, tx = Math.max(l, Math.min(w - tw - 4, sx - tw / 2)), ty = Math.max(3, sy - (pendingTip ? 55 : 73));
    const tip = pendingTip ? `<text x="${tx + tw / 2}" y="${ty + 15}" text-anchor="middle">${dateList[selectedIndex].getMonth() + 1}/${dateList[selectedIndex].getDate()}</text><text x="${tx + tw / 2}" y="${ty + 31}" text-anchor="middle">시세 수집 대기</text><text x="${tx + tw / 2}" y="${ty + 44}" text-anchor="middle">오늘 경락가 미반영</text>` : `<text x="${tx + tw / 2}" y="${ty + 13}" text-anchor="middle">${dateList[selectedIndex].getMonth() + 1}/${dateList[selectedIndex].getDate()}</text><text x="${tx + tw / 2}" y="${ty + 29}" text-anchor="middle">최고 ${won(values[selectedIndex])} · 평균 ${won(points[selectedIndex].avg)}</text><text class="chart-compare" x="${tx + tw / 2}" y="${ty + 47}" text-anchor="middle">${comparison}</text><text class="chart-compare-note" x="${tx + tw / 2}" y="${ty + 60}" text-anchor="middle">특등급 최고가 대비</text>`;
    svg.innerHTML = `${grid}<rect class="chart-surface" data-grade-surface x="${l}" y="${t}" width="${cw}" height="${ch}"/>${closedBands}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${solid}"/>${pending ? `<polyline class="chart-pending-line" points="${pending}"/>` : ""}${dots}<g class="chart-tooltip"><rect x="${tx}" y="${ty}" width="${tw}" height="${th}" rx="7"/><path d="M ${sx - 5} ${ty + th} L ${sx + 5} ${ty + th} L ${sx} ${ty + th + 5}Z"/>${tip}</g>${labels}`;
    card.dataset.gradeSelectedIndex = selectedIndex; card.querySelectorAll("[data-grade-value]").forEach(b => b.classList.toggle("active", b.dataset.value === grade));
    const sub = card.querySelector(".market-top p"), prefix = sub?.textContent.split(" · ")[0], pendingToday = points.at(-1)?.status === "pending";
    if (sub) sub.textContent = `${prefix} · ${gradeLabel(grade)}등급 · 최근 ${points.length}일 중 실제 거래 ${points.filter(p => p.status === "traded").length}일${pendingToday ? " · 오늘 수집 대기" : ""}`;
    const notice = card.closest("#marketView")?.querySelector(".notice"); if (notice && !notice.dataset.marketStatusEnhanced) { notice.innerHTML = "시세는 가락시장 실제 거래 자료입니다.<br><b>회색 점선·대기</b>는 오늘 경락가 수집 전, <b>빨간 점·휴</b>는 거래 없는 날입니다. 날짜를 누르면 상세 상태를 확인할 수 있어요."; notice.dataset.marketStatusEnhanced = "true"; }
    priceInfo(card, points, grade, selectedIndex);
  }

  async function charts(card) {
    const days = daysOf(card), item = card.dataset.marketId, dateList = dates(days), responses = await Promise.all(dateList.map(d => fetch(`/api/market?item=${encodeURIComponent(item)}&date=${d.toISOString().slice(0, 10).replaceAll("-", "")}`).then(r => r.json()))), units = [...new Set(responses.flatMap(r => (r.resultData || []).map(row => String(row.U_NAME || "").trim())).filter(Boolean))], selectedUnit = localStorage.getItem(`veggi-market-unit-${item}`) || units[0], result = { _units: units, _unit: selectedUnit };
    ["특", "상", "중"].forEach(grade => { const raw = responses.map((response, i) => { const row = (response.resultData || []).find(value => String(value.G_NAME || "").trim() === apiGrade(grade) && String(value.U_NAME || "").trim() === selectedUnit) || null; return { row, status: row ? "traded" : (response.collected || dateList[i].getDay() === 0 ? "closed" : "pending") }; }), first = raw.find(value => value.row); if (!first) return; let last = { max: number(first.row.MA_P), avg: number(first.row.AV_P), unit: String(first.row.U_NAME || "").trim() }; result[grade] = raw.map(value => { if (value.row) last = { max: number(value.row.MA_P), avg: number(value.row.AV_P), unit: String(value.row.U_NAME || "").trim() }; return { ...last, status: value.status }; }); });
    if (!["특", "상", "중"].some(grade => result[grade])) throw Error("no data"); return result;
  }
  function markGrades(card, data) { card.querySelectorAll("[data-grade-value]").forEach(b => { const value = b.dataset.value, label = gradeLabel(value), ok = Boolean(data[value]); b.disabled = !ok; b.classList.toggle("unavailable", !ok); b.textContent = ok ? label : `${label} 없음`; b.setAttribute("aria-label", ok ? `${label}등급 선택` : `${label}등급 거래 없음`); }); }
  function markUnits(card, data) { card.querySelector(".market-unit-picker")?.remove(); if (data._units.length < 2) return; const picker = document.createElement("div"); picker.className = "market-unit-picker"; picker.innerHTML = `<span>거래단위</span>${data._units.map(unit => `<button type="button" data-market-unit="${unit}" class="${unit === data._unit ? "active" : ""}">${unit}</button>`).join("")}<small><b>●</b> 빨강: 거래 없음 · 회색: 수집 대기</small>`; card.querySelector(".market-top")?.after(picker); }
  async function selectGrade(button) { const card = button.closest(".market-card"); if (!card || button.disabled) return; const wanted = button.dataset.value; try { let data = cache.get(card); if (!data) { data = await charts(card); cache.set(card, data); } markUnits(card, data); markGrades(card, data); const grade = data[wanted] ? wanted : ["특", "상", "중"].find(g => data[g]); draw(card, data[grade], grade, Number(card.dataset.gradeSelectedIndex ?? data[grade].length - 1), data); } catch { card.querySelector("svg")?.replaceChildren(); const note = card.querySelector(".market-advice"); if (note) note.textContent = `${gradeLabel(wanted)}등급의 실제 거래 데이터가 없습니다.`; } }
  function selectPoint(card, index) { const data = cache.get(card), grade = card?.querySelector("[data-grade-value].active")?.dataset.value; if (data?.[grade]) draw(card, data[grade], grade, index, data); }
  window.addEventListener("click", e => { const b = e.target.closest?.("[data-grade-value]"); if (!b) return; e.preventDefault(); e.stopImmediatePropagation(); selectGrade(b); }, true);
  window.addEventListener("click", e => { const p = e.target.closest?.("[data-grade-point]"); if (!p) return; e.preventDefault(); e.stopImmediatePropagation(); selectPoint(p.closest(".market-card"), Number(p.dataset.gradePoint)); }, true);
  window.addEventListener("click", e => { const b = e.target.closest?.("[data-market-unit]"); if (!b) return; e.preventDefault(); e.stopImmediatePropagation(); const card = b.closest(".market-card"); localStorage.setItem(`veggi-market-unit-${card.dataset.marketId}`, b.dataset.marketUnit); window.dispatchEvent(new Event("veggi-market-history-ready")); }, true);
  const indexAtPointer = (svg, clientX) => { const box = svg.getBoundingClientRect(), days = daysOf(svg.closest(".market-card")), x = (clientX - box.left) / box.width * 350; return Math.max(0, Math.min(days - 1, Math.round((x - 38) / 298 * (days - 1)))); };
  let dragging = null;
  window.addEventListener("pointerdown", e => { const svg = e.target.closest?.(".market-card svg"); if (!svg || e.button > 0) return; const card = svg.closest(".market-card"); dragging = { pointerId: e.pointerId, svg, card, index: -1 }; svg.setPointerCapture?.(e.pointerId); const index = indexAtPointer(svg, e.clientX); dragging.index = index; selectPoint(card, index); e.preventDefault(); }, true);
  window.addEventListener("pointermove", e => { if (!dragging || dragging.pointerId !== e.pointerId) return; const index = indexAtPointer(dragging.svg, e.clientX); if (index !== dragging.index) { dragging.index = index; selectPoint(dragging.card, index); } e.preventDefault(); }, true);
  window.addEventListener("pointerup", e => { if (!dragging || dragging.pointerId !== e.pointerId) return; dragging.svg.releasePointerCapture?.(e.pointerId); dragging = null; }, true);
  window.addEventListener("pointercancel", () => { dragging = null; }, true);
  window.addEventListener("click", e => { const s = e.target.closest?.("[data-grade-surface]"); if (!s) return; e.preventDefault(); e.stopImmediatePropagation(); selectPoint(s.closest(".market-card"), indexAtPointer(s.ownerSVGElement, e.clientX)); }, true);
  const prepare = () => document.querySelectorAll(".market-card").forEach(card => { if (prepared.has(card)) return; prepared.add(card); const active = card.querySelector("[data-grade-value].active") || card.querySelector('[data-grade-value][data-value="특"]'); if (active) selectGrade(active); });
  // 전역 DOM 감시는 모바일에서 렌더링 반복을 일으킨 적이 있어 사용하지 않는다.
  window.addEventListener("veggi-market-history-ready", prepare);
  window.addEventListener("click", event => { if (event.target.closest?.('[data-view="marketView"]')) setTimeout(prepare, 0); });
  prepare();
})();
